# NUMPY

**What is Numpy?**

Ans: NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. … A powerful N-dimensional array object. Sophisticated (broadcasting) functions.

**Why NumPy is used in Python?**

Ans: NumPy is a package in Python used for Scientific Computing. NumPy package is used to perform different operations. The ndarray (NumPy Array) is a multidimensional array used to store values of same datatype. These arrays are indexed just like Sequences, starts with zero.

**How to Install Numpy in Windows?**

Ans: Step 1: Download Python for Windows 10/8/7. First, download the Python executable binaries on your Windows system from the official download the page of the Python. … Step 2: Run the Python executable installer. … Step 3: Install pip on Windows 10/8/7. … Step 4: Install Numpy in Python using pip on Windows 10/8/7.

Installation Process of Numpy.. step1: Open the terminal step2: type pip install numpy

## Numpy

**NumPy (Numerical Python) provides:**

-The ndarray — a fast, memory-efficient N-dimensional array object.

-Vectorized operations (C-backed) via ufuncs for elementwise computations.

-Broadcasting rules to operate on arrays of different shapes.

-Tools for linear algebra, random number generation, FFTs, and I/O.

- Numpy stands for numerical python
- Building block for many other libraries like Pandas, Matplotlib etc

In [3]:
#Import library
import numpy as np

In [4]:
#!pip install numpy=1.26
#pip install numpy

In [5]:
np.__version__
#import numpy==1.16 
#!pip install --force-reinstall numpy==1.20   #Force reinstall a specific version

'2.1.3'

## Data types available in numpy - Array
- Scalars
- Vectors or 1-d arrays
- Matrices or 2-d arrays
- Higher dimensional arrays

 **ndarray**

Homogeneous: every element has the same dtype (e.g., float64, int32).

**Attributes:**

-ndarray.shape — tuple for dimensions (rows, cols, ...).

-ndarray.ndim — number of dimensions.

-ndarray.size — total number of elements.

-ndarray.dtype — data type of elements.

-ndarray.itemsize — bytes per element.

-ndarray.nbytes — total bytes (size * itemsize).

-ndarray.strides — bytes to step in each dimension.

In [ ]:
np.array()

In [7]:
#Scalar - That doesn't have direction and has only magnitude
# np.array is the function used to create a numpy array
arr1 = np.array(10)

In [8]:
arr1

array(10)

In [9]:
type(arr1)  #datatype of the variable as a whole

numpy.ndarray

In [11]:
#Creating a 1-d array using a list
arr2 = np.array([1,2,3,4])

In [12]:
arr2

array([1, 2, 3, 4])

In [13]:
# Creating a 1-d array using a tuple
arr2 = np.array((2,2,3,4))

In [14]:
arr2.ndim

1

In [15]:
#Creating a 2-d array - Matrix
arr3 = np.array([[1,2,3,True],[2,3,4,5]])

In [16]:
arr3.dtype

dtype('int64')

In [17]:
arr3.size

8

In [18]:
# Attributes of a numpy array
#dtype  - datatype of elements in it.
#ndim - Dimension of the array
#size - No. of the elements in the array
#shape - how many elements in each dimension

In [19]:
#arr1 is a scalar. arr1 = 10
arr1.dtype  #datatype of elements inside the array

dtype('int64')

In [20]:
arr4 = np.array([1,2,3,1.234])
print(type(arr4), arr4.dtype)

<class 'numpy.ndarray'> float64


In [21]:


arr1.ndim #no. of the dimensions present in the array

0

In [22]:
arr1.shape #Gives how the elements are layered in each dimension

()

In [23]:
arr1.size #total number of elements in the array

1

In [24]:
a = [[1,2,3],[4,5,6],[7,6,5]]
len(a)

3

In [25]:
np.array(a).shape

(3, 3)

In [26]:
b = np.array(a)
print(b.size, b.shape)

9 (3, 3)


In [27]:
arr2

array([2, 2, 3, 4])

In [28]:
print(arr2,type(arr2))

[2 2 3 4] <class 'numpy.ndarray'>


In [29]:
print('datatypes of elements:', arr2.dtype, 'dimension:', arr2.ndim, 'shape:', arr2.shape,'size:' ,arr2.size)

datatypes of elements: int64 dimension: 1 shape: (4,) size: 4


In [30]:
print(arr3,type(arr3))

[[1 2 3 1]
 [2 3 4 5]] <class 'numpy.ndarray'>


In [31]:
arr3.shape

(2, 4)

In [32]:
print('datatypes of elements:', arr3.dtype, 'dimension:', arr3.ndim, 'shape:', arr3.shape,'size:' ,arr3.size)

datatypes of elements: int64 dimension: 2 shape: (2, 4) size: 8


In [33]:
arr6 = np.array([[[11,22],[1,2],[111,222]],[[5,7],[6,5],[4,3]]])
arr6

array([[[ 11,  22],
        [  1,   2],
        [111, 222]],

       [[  5,   7],
        [  6,   5],
        [  4,   3]]])

In [34]:
arr6.shape

(2, 3, 2)

In [37]:
print('datatypes of elements:', arr6.dtype, 'dimension:', arr6.ndim, 'shape:', arr6.shape,'size:' ,arr6.size)

datatypes of elements: int64 dimension: 3 shape: (2, 3, 2) size: 12


In [38]:
# A 2-d array is called a matrix

In [39]:
arr = np.array([[[[[[[[[[1,2]]]]]]]]]])

In [40]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[[[[[[[[1 2]]]]]]]]]] <class 'numpy.ndarray'> datatypes of elements: int64 dimension: 10 shape: (1, 1, 1, 1, 1, 1, 1, 1, 1, 2) size: 2


In [41]:
arr = np.array([[[1,2,3,4],[2,3,4,5],[1,2,3,4]],[[4,5,6,7],[8,9,7,6],[5,4,3,2]]])
arr

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[4, 5, 6, 7],
        [8, 9, 7, 6],
        [5, 4, 3, 2]]])

In [42]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[1 2 3 4]
  [2 3 4 5]
  [1 2 3 4]]

 [[4 5 6 7]
  [8 9 7 6]
  [5 4 3 2]]] <class 'numpy.ndarray'> datatypes of elements: int64 dimension: 3 shape: (2, 3, 4) size: 24


In [43]:
arr = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])

In [44]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]] <class 'numpy.ndarray'> datatypes of elements: int64 dimension: 3 shape: (2, 2, 2) size: 8


In [45]:
arr = np.array({1,2})

In [46]:
arr

array({1, 2}, dtype=object)

In [47]:
arr = np.array({'A':1,'B':2})
arr

array({'A': 1, 'B': 2}, dtype=object)

In [48]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

{'A': 1, 'B': 2} <class 'numpy.ndarray'> datatypes of elements: object dimension: 0 shape: () size: 1


### Reshape function: Lets you change the shape of array

In [49]:
arr = np.array([1,2,3,4])

In [50]:
print(arr,'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[1 2 3 4] dimension: 1 shape: (4,) size: 4


In [51]:
arr

array([1, 2, 3, 4])

In [107]:
arr.reshape((1,4))

array([[1, 2, 3, 4]])

In [109]:
arr.reshape((1,1,1,4,1,1,1))

array([[[[[[[1]]],


          [[[2]]],


          [[[3]]],


          [[[4]]]]]]])

In [111]:
arr.reshape((1,4))

array([[1, 2, 3, 4]])

In [110]:
arr.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr

In [112]:
arr = np.array([1,2,3,4])
print(arr,'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[1 2 3 4] dimension: 1 shape: (4,) size: 4


In [113]:
arr1 = arr.reshape((2,2))

In [114]:
print(arr1,'dimension:', arr1.ndim, 'shape:', arr1.shape,'size:' ,arr1.size)

[[1 2]
 [3 4]] dimension: 2 shape: (2, 2) size: 4


In [115]:
arr = np.array([1,2,3,4])

In [ ]:
arr2 = arr.reshape((1,2,2,1))
print(arr2,'dimension:', arr2.ndim, 'shape:', arr2.shape,'size:' ,arr2.size)

In [120]:
list(range(1,100,10))

[1, 11, 21, 31, 41, 51, 61, 71, 81, 91]

### Built in arrays:
- arange - a 1-d array with uniformly spaced numbers between a start and stop value. Integers
  - np.arange(start,stop,step)
  - Can be used in combination with a reshape function to create an array of any dimension. 
- zeros, ones - zero  matrix and ones matrix
  - np.zeros(shape tuple,dtype)
  - np.ones(shape tuple,dtype)
- linspace - Generate a count of samples between start and stop values
  - np.linspace(start,stop,count)
  - Stop is inclusive
- eye - Create an identity matrix
  - (defaults square matrix, can be made as rectangular matrix)

In [124]:
# np.arange(start,stop,step)  : Start - defaults to 0, step value defaults to 1, stop is exclusive
arr = np.arange(3,15,2)
arr

array([ 3,  5,  7,  9, 11, 13])

In [122]:
arr = np.arange(2,15,0.5)
arr

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [128]:
arr = np.arange(-1,6,-1)
arr

array([], dtype=int32)

In [126]:
arr = np.arange(-1,-6,-1)
arr

array([-1, -2, -3, -4, -5])

In [130]:
np.arange(2,40,7)
arr = np.arange(2,30,3).reshape((5,2))
arr

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])

In [131]:
arr = np.arange(1.4,3.7,0.58)
arr

array([1.4 , 1.98, 2.56, 3.14])

In [136]:
#arr = np.zeros(shape, datatype)
arr = np.zeros((3,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [137]:
arr = np.zeros((4,5,6),dtype=float)
arr

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [138]:
#np.ones(shape tuple,dtype)
arr= np.ones(4,dtype=int)
arr

array([1, 1, 1, 1])

In [139]:
'a'+str(2)

'a2'

In [140]:
arr= np.ones((4,),dtype=int)
arr

array([1, 1, 1, 1])

In [141]:
arr = np.ones((4,5,6),dtype=float)
arr

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [142]:
#np.eye(size, offset)
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [159]:
i =0
while i < 4:
    print(f"if k={i}\n", np.eye(5,k=i,dtype=int))
    i = i +1

if k=0
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
if k=1
 [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
if k=2
 [[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
if k=3
 [[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [153]:
np.eye(5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [162]:
#np.linspace(start,stop,count) start defaults to 0, count defaults to 50, stop is inclusive, endpoint=False makes stop exclusive
arr = np.linspace(2,3,10,endpoint=False,retstep=True)
arr

(array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]), 0.1)

In [163]:
arr = np.linspace(3,3.1,2)
arr

array([3. , 3.1])

In [164]:
arr = np.linspace(2,40,22,retstep=True, dtype='int')
arr

(array([ 2,  3,  5,  7,  9, 11, 12, 14, 16, 18, 20, 21, 23, 25, 27, 29, 30,
        32, 34, 36, 38, 40]),
 1.8095238095238095)

### Operations on numpy arrays - Broadcasting 
- Broadcasting is a feature of numpy that allows operations on elements of array without needing a loop.
- Stretching is a form of broadcasting where matrices of different dimensions can be operated on.
  

In [170]:
np.array([1,2,3]) ** np.array([2,3,4])

array([ 1,  8, 81])

In [171]:
arr = np.array([[1,2,3,4,5],[3,4,5,6,7]])

In [173]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [174]:
arr+1
#arr = arr+1

array([[2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [175]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [176]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14]])

In [177]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [ 9, 16, 25, 36, 49]])

In [2]:
# Stretching
arr

NameError: name 'arr' is not defined

In [181]:
arr.shape

(2, 5)

In [184]:
arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [185]:
arr2.shape

(5,)

In [186]:
arr+arr2

array([[11, 22, 33, 44, 55],
       [13, 24, 35, 46, 57]])

In [187]:
arr3 = np.array([1,2,3,4,5,6,7])

In [189]:
arr3.shape

(7,)

In [190]:
arr.shape

(2, 5)

In [1]:
arr+arr3

NameError: name 'arr' is not defined

In [216]:
k1= np.array([[1,2.3],[2,True]])
k1.shape

(2, 2)

In [217]:
k2= np.array([[1,2],[4,5]])
k2.shape

(2, 2)

In [218]:
k1 * k2

array([[1. , 4.6],
       [8. , 5. ]])

In [219]:
arr**3

array([[  1,   8,  27,  64, 125],
       [ 27,  64, 125, 216, 343]], dtype=int32)

### Random module
#### Functions 
- rand: Generate a float array of chosen dimension of values between 0 and 1
- randn: Generates a array of chosen dimension with values that belong a Standard normal distribution
- randint: Generates a array of integers between chosen values

In [223]:
# rand
#from numpy import random
np.random.rand(3,4)   # 0 is inclusive, 1 is exclusive

array([[0.53978832, 0.2056675 , 0.42029126, 0.05340061],
       [0.19075347, 0.06144214, 0.98050514, 0.42179178],
       [0.34374227, 0.02878043, 0.3600169 , 0.64806476]])

In [224]:
np.random.randn(3,4) # -3 to +3

array([[ 1.75061693,  1.10651601,  1.18402112, -1.52063775],
       [-1.4213    , -1.46845672,  0.31824218,  0.92959552],
       [-0.78520106,  0.09336133, -0.13345231,  0.3117169 ]])

In [225]:
#np.random.randint(low,high,count)
np.random.randint(2,50,12)

array([24, 30, 25, 29,  6, 48, 14, 37, 15, 45, 47, 16])

In [117]:
np.random.randint(1,7,40)  #Generate 40 random integers between 1 and 7. End point is exclusive

array([5, 2, 4, 1, 6, 2, 1, 3, 6, 5, 2, 5, 6, 1, 2, 2, 4, 1, 4, 5, 5, 4,
       4, 3, 5, 5, 3, 2, 6, 5, 2, 4, 4, 6, 1, 2, 1, 3, 3, 6])

In [226]:
np.random.randint(2,10,(2,5))     #Generate a array of shape (2,5) with random integers from 2 to 10, 10 is exclusive

array([[3, 8, 3, 6, 6],
       [2, 6, 3, 2, 6]])

### Properties of numpy arrays
-min, max, argmin, argmax, mean, median

In [229]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [230]:
l1 = [1,4,2,5,3,67,4,8]
min(l1)

1

In [231]:
max(l1)

67

In [232]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [233]:
#arr.min()
np.min(arr)

1

In [234]:
#arr.max()
np.max(arr)

7

In [235]:
arr.shape

(2, 5)

In [239]:
#arr.argmin()
np.argmin(arr)

0

In [240]:
#arr.argmax()
np.argmax(arr)

9

In [241]:
#arr.mean()
np.mean(arr)

4.0

In [242]:
np.median(arr)


4.0

In [251]:
#np.where - lets you find the element meeting a condition
arr = np.array([55,63,79,38,24,16,84,93,105])

In [252]:
arr.shape

(9,)

In [253]:
arr

array([ 55,  63,  79,  38,  24,  16,  84,  93, 105])

In [255]:
arr[arr >65]

array([ 79,  84,  93, 105])

In [257]:
np.where(arr >65)

(array([2, 6, 7, 8], dtype=int64),)

In [258]:
arr[np.where(arr>65)]

array([ 79,  84,  93, 105])

In [259]:
np.where((arr>4) & (arr<9))

(array([], dtype=int64),)

In [265]:
np.where(arr%2==0)

(array([3, 4, 5, 6], dtype=int64),)

In [264]:
arr[np.where(arr%2==0)]

array([38, 24, 16, 84])

In [ ]:
print(np.where(arr>7),'\n',arr[np.where(arr>7)])

In [280]:
a = np.array([[22,22,3,44,55],[2,3,4,5,6]])
a

array([[22, 22,  3, 44, 55],
       [ 2,  3,  4,  5,  6]])

In [281]:
a%2==0

array([[ True,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [282]:
np.where(a%2==0)

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 3, 0, 2, 4], dtype=int64))

In [285]:
a.shape

(2, 5)

In [298]:
a.reshape((-1,))

array([22, 22,  3, 44, 55,  2,  3,  4,  5,  6])

In [299]:
np.where((a.reshape((-1,)))%2==0)

(array([0, 1, 3, 5, 7, 9], dtype=int64),)

In [308]:
#np.where can function like a if-else statement
a = np.array([11,22,33,44,55,66,77,88])
a[np.where(a>55)]

array([66, 77, 88])

### Indexing a numpy array
- arr[index]
- arr[d0index][d1index]...

In [309]:
arr

array([ 55,  63,  79,  38,  24,  16,  84,  93, 105])

In [310]:
arr.shape

(9,)

In [187]:
len([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,4,6,8,9,0,2,3,5,11])

30

In [332]:
k9 =np.array([9,44,32,221,33,55,22,55])

In [335]:
k9[1:4]

array([ 44,  32, 221])

In [330]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,4,6,8,9,0,2,3,5,11]).reshape(5,6)

In [321]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10,  1,  2],
       [ 3,  4,  5,  6,  7,  8],
       [ 9, 10,  1,  4,  6,  8],
       [ 9,  0,  2,  3,  5, 11]])

In [323]:
arr[1,3]

10

In [324]:
arr[1][3]

10

In [339]:
arr[2:4,2:4]

array([[5, 6],
       [1, 4]])

In [343]:
arr[0,2:5]

array([3, 4, 5])

In [340]:
arr[0][2:5]

array([3, 4, 5])

In [342]:
arr[0][1]

2

In [ ]:
arr[0][1]

In [344]:
arr[0][0]

1

In [345]:
arr[0,0:1]

array([1])

In [348]:
arr[0,0:1]

array([1])

In [349]:
arr[0][0:1]

array([1])

In [350]:
arr[0][0:1]

array([1])

In [352]:
print(arr[0][0:1])

[1]


#### Understanding notation for slicing

In [ ]:
print(arr[0][1])

In [ ]:
print(arr[0][1:2])

In [ ]:
print(arr[0,1:2])

In [354]:
print(arr[0][1])

2


In [353]:
print(arr[0][1:2])

[2]


In [355]:
print(arr[0,1:2])

[2]


In [356]:
arr[0][0:1]

array([1])

In [357]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10,  1,  2],
       [ 3,  4,  5,  6,  7,  8],
       [ 9, 10,  1,  4,  6,  8],
       [ 9,  0,  2,  3,  5, 11]])

### Copy vs View

In [387]:
arr = np.array([1,2,3])

In [388]:
arr+1

array([2, 3, 4])

In [389]:
arr

array([1, 2, 3])

In [393]:
xyz = arr

In [395]:
xyz

array([1, 2, 3])

In [396]:
arr

array([1, 2, 3])

In [397]:
arr[2] = 10

In [398]:
arr

array([ 1,  2, 10])

In [399]:
xyz

array([ 1,  2, 10])

In [400]:
xyz[1] = 22

In [401]:
xyz

array([ 1, 22, 10])

In [402]:
arr

array([ 1, 22, 10])

In [225]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [404]:
arr = np.array([1,2,3])
abc = arr.copy()
abc

array([1, 2, 3])

In [405]:
arr

array([1, 2, 3])

In [406]:
arr[2] = 10
arr

array([ 1,  2, 10])

In [407]:
abc

array([1, 2, 3])

In [ ]:
arr3 = arr.view()

In [ ]:
import statistics
a = [1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,2,3,2,3]
statistics.multimode(a)

In [ ]:
a = [1,2,3,4]

In [ ]:
type(a)

In [ ]:
a = []
for i in range(10):
    a.append(int(input('Enter a number')))
b = np.array(a)

In [ ]:
b

In [ ]:
a = input('Enter a list:')
b = list(a)

In [ ]:
b

In [ ]:
type(b)