In [4]:
import pandas as pd
import numpy as np

In [5]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
##create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['columns1','columns2','columns3','columns4'])

In [8]:
df.head()

columns1  columns2  columns3  columns4
row1         0         1         2         3
row2         4         5         6         7
row3         8         9        10        11
row4        12        13        14        15
row5        16        17        18        19

In [9]:
df.tail()

columns1  columns2  columns3  columns4
row1         0         1         2         3
row2         4         5         6         7
row3         8         9        10        11
row4        12        13        14        15
row5        16        17        18        19

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   columns1  5 non-null      int64
 1   columns2  5 non-null      int64
 2   columns3  5 non-null      int64
 3   columns4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [12]:
df.describe()

columns1   columns2   columns3   columns4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [13]:
##Indexing
#Columnname rowindex[loc],rowindex columnindex Number[.iloc]
df.head()

columns1  columns2  columns3  columns4
row1         0         1         2         3
row2         4         5         6         7
row3         8         9        10        11
row4        12        13        14        15
row5        16        17        18        19

In [14]:
##columnname
type(df['columns1'])

pandas.core.series.Series

In [15]:
df[['columns1','columns2','columns3']]

columns1  columns2  columns3
row1         0         1         2
row2         4         5         6
row3         8         9        10
row4        12        13        14
row5        16        17        18

In [16]:
#by using row index name
df.loc['row3']

columns1     8
columns2     9
columns3    10
columns4    11
Name: row3, dtype: int64

In [17]:
df.loc[['row3','row4']]

columns1  columns2  columns3  columns4
row3         8         9        10        11
row4        12        13        14        15

In [18]:
df.iloc[2:4,0:2]

columns1  columns2
row3         8         9
row4        12        13

In [19]:
df.iloc[2:,1:]

columns2  columns3  columns4
row3         9        10        11
row4        13        14        15
row5        17        18        19

In [20]:
df.iloc[:,1:]

columns2  columns3  columns4
row1         1         2         3
row2         5         6         7
row3         9        10        11
row4        13        14        15
row5        17        18        19

In [21]:
#convert into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [22]:
df.isnull().sum()

columns1    0
columns2    0
columns3    0
columns4    0
dtype: int64

In [23]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['row1','row2'],columns=['columns1','columns2','columns3'])

In [24]:
df

columns1  columns2  columns3
row1         1       NaN         2
row2         1       3.0         4

In [25]:
df.isnull().sum()

columns1    0
columns2    1
columns3    0
dtype: int64

In [26]:
df.isnull().sum()==0

columns1     True
columns2    False
columns3     True
dtype: bool

In [27]:
df.isnull()

columns1  columns2  columns3
row1     False      True     False
row2     False     False     False

In [28]:
df['columns3'].value_counts()

columns3
2    1
4    1
Name: count, dtype: int64

In [29]:
df['columns2'].unique()

array([nan,  3.])

In [30]:
df>2

columns1  columns2  columns3
row1     False     False     False
row2     False      True      True

In [32]:
df[df['columns2']>2]

columns1  columns2  columns3
row2         1       3.0         4