# Tree Implementation

In [2]:
import pickle   # importing pickle for saving and loading machine learning models
from sklearn.model_selection import train_test_split  # importing train_test_split for spliting the data into training and testing
from imblearn.over_sampling import SMOTE  # importing SMOTE for Balancing the Data
import warnings
warnings.filterwarnings('ignore')

In [3]:
from preprocessing import *

ModuleNotFoundError: No module named 'preprocessing'

In [45]:
with open('Tree_CT.pkl','rb') as f:
    pre = pickle.load(f)

In [46]:
pre

ColumnTransformer(force_int_remainder_cols=True, n_jobs=None,
                  remainder='passthrough', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('OHE columns',
                                 OneHotEncoder(categories='auto', drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               feature_name_combiner='concat',
                                               handle_unknown='error',
                                               max_categories=None,
                                               min_frequency=None,
                                               sparse_output=True),
                                 ['Busine...
                                                unknown_value=None),
                                 ['OverTime']),
                                ('Standard_scaler',
                                 StandardScaler(copy=True, with_mean=True,
                                                with_std=True),
                                 ['Age', 'DailyRate', 'DistanceFromHome',
                                  'MonthlyRate', 'HourlyRate',
                                  'NumCompaniesWorked', 'TotalWorkingYears',
                                  'YearsAtCompany', 'YearsInCurrentRole',
                                  'YearsSinceLastPromotion',
                                  'YearsWithCurrManager',
                                  'PercentSalaryHike'])],
                  verbose=False, verbose_feature_names_out=True)

In [47]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 06A3-F423

 Directory of C:\Users\Art Computer\Downloads

11/12/2025  01:09 PM    <DIR>          .
11/12/2025  01:09 PM    <DIR>          ..
11/12/2025  12:23 PM    <DIR>          .ipynb_checkpoints
10/09/2025  12:39 PM            67,180 23sep (1).ipynb
09/23/2025  10:42 PM            18,259 23sep.ipynb
10/09/2025  12:36 PM            11,641 7oct.ipynb
11/05/2025  11:36 PM             5,166 Advertising.csv
10/22/2025  09:53 PM            25,410 Assignment.ipynb
11/04/2025  12:17 PM           397,346 Feature_engineering_and_PCA_Class.ipynb
11/09/2025  12:17 AM           709,644 heart analyse (1).ipynb
11/12/2025  12:01 PM           695,439 heart analyse.ipynb
11/08/2025  06:18 PM            11,328 heart.csv
11/07/2025  04:19 PM           176,254 house-prices-advanced-regression-techniques-publicleaderboard-2025-11-07T10_49_38.zip
11/10/2025  01:13 PM           227,977 HR.csv
11/04/2025  12:58 PM            41,032 ipynb_checkpoint

In [48]:
with open('Processed_data_HR.pkl','rb') as f:
    df = pickle.load(f)

In [49]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female  ...                  3                         1   
1       Male  ...                  4                         4   
2       Male  ...                  3                         2   
3     Female  ...                  3                         3   
4       Male  ...                  3                         4   
...      ...  ...                ...                       ...   
1465    Male  ...                  3                         3   
1466    Male  ...                  3                         1   
1467    Male  ...                  4                         2   
1468    Male  ...                  3                         4   
1469    Male  ...                  3                         1   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    0                 8                      0   
1                    1                10                      3   
2                    0                 7                      3   
3                    0                 8                      3   
4                    1                 6                      3   
...                ...               ...                    ...   
1465                 1                17                      3   
1466                 1                 9                      5   
1467                 1                 6                      0   
1468                 0                17                      3   
1469                 0                 6                      3   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  1               6                   4   
1                  3              10                   7   
2                  3               0                   0   
3                  3               8                   7   
4                  3               2                   2   
...              ...             ...                 ...   
1465               3               5                   2   
1466               3               7                   7   
1467              

In [50]:
X = df.drop("Attrition",axis=1)     # Extract the features (all columns except Attritions) from the dataset
y = df["Attrition"].map({"No":0,"Yes":1})  # Extract the target variable from the dataset with converting 0 and 1.

In [51]:
df.Attrition.value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [52]:
# Spliting the data into train and test
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=33)

In [53]:
# Transform the training data using the preprocessor object or PipeLine
processed_x_train = pre.fit_transform(x_train)

In [54]:
processed_x_train.shape

(1102, 49)

In [55]:
processed_x_train[0]

array([ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  1.        , -0.3098615 ,  1.3622128 ,  1.16898078,
       -1.33034804,  0.05469197,  2.11675505, -0.30137951, -0.32177888,
       -0.60819028, -0.68968387, -0.03669649, -0.5936842 ,  3.        ,
        1.        ,  4.        ,  2.        ,  4.        ,  3.        ,
        2.        ,  0.        ,  3.        ,  2.        ])

### 
Model Building

In [56]:
import sklearn
sklearn.set_config(print_changed_only=False)

In [57]:
from sklearn.tree import DecisionTreeClassifier        #importing decision tree from sklearn.tree
dt=DecisionTreeClassifier()             #object creation for decision tree
dt.fit(processed_x_train,y_train)    # sample_weight=sample_weights    #train the model

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=None, splitter='best')

In [58]:
#Prediction
processed_x_test = pre.transform(x_test)
y_pred=dt.predict(processed_x_test)

In [59]:
#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.7744565217391305 
Precision: 0.3561643835616438 
Recall Score: 0.41935483870967744 
F1 Score 0.3851851851851852 
Confusion Matrix: 
 [[259  47]
 [ 36  26]]
              precision    recall  f1-score   support

           0       0.88      0.85      0.86       306
           1       0.36      0.42      0.39        62

    accuracy                           0.77       368
   macro avg       0.62      0.63      0.62       368
weighted avg       0.79      0.77      0.78       368



In [60]:
results = pd.DataFrame(index=['Accuracy','F1'])
results['DT/imb'] = [acc,f1]
results

NameError: name 'pd' is not defined

In [ ]:
#Prediction on Training data - Test of overfitting
y_pred1=dt.predict(processed_x_train)

#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_train,y_pred1)
pr = precision_score(y_train,y_pred1)
re = recall_score(y_train,y_pred1)
f1 = f1_score(y_train,y_pred1)
cm = confusion_matrix(y_train,y_pred1)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_train,y_pred1))

In [61]:
results['DT/Train'] = [acc,f1]
results

NameError: name 'results' is not defined

In [62]:
y_train.value_counts()

Attrition
0    927
1    175
Name: count, dtype: int64

In [63]:
## Data Balancing and Creating Model
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)

dt_bal=DecisionTreeClassifier()            
dt_bal.fit(x_smote,y_smote)   #Training the model again with smote balanced data

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=None, splitter='best')

In [64]:
y_smote.value_counts()

Attrition
1    927
0    927
Name: count, dtype: int64

In [65]:
#Prediction
#processed_x_test = pre.transform(x_test)
y_pred=dt_bal.predict(processed_x_test)

In [66]:
#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.7880434782608695 
Precision: 0.38235294117647056 
Recall Score: 0.41935483870967744 
F1 Score 0.4 
Confusion Matrix: 
 [[264  42]
 [ 36  26]]
              precision    recall  f1-score   support

           0       0.88      0.86      0.87       306
           1       0.38      0.42      0.40        62

    accuracy                           0.79       368
   macro avg       0.63      0.64      0.64       368
weighted avg       0.80      0.79      0.79       368



In [67]:
results['DT/Smote'] = [acc,f1]
results

NameError: name 'results' is not defined

In [ ]:
from sklearn.model_selection import GridSearchCV
#creating dictionary--> key value pair of hyperparameters having key as parameter and values as its values
params = {
    "criterion":("gini", "entropy"), #Split criterion
    "splitter":("best", "random"),  #searches the features for a split
    "max_depth":(list(range(1,20,2))),  #depth of tree range from 1 to 19
    "min_samples_split":[5,7,10,12,15],    #the minimum number of samples required to split internal node
    "min_samples_leaf":list(range(3, 20)), #minimum number of samples required to be at a leaf node,we are passing list which is range from 1 to 19
}


tree_clf = DecisionTreeClassifier()                # object creation for decision tree with random state 3
tree_cv = GridSearchCV(tree_clf, params, scoring="f1", n_jobs=-1, verbose=5, cv=2)

In [68]:
tree_cv.fit(processed_x_train,y_train)    # training data on gridsearch cv
best_params = tree_cv.best_params_    # it will give you best parameters
print(f"Best paramters: {best_params})")   # printing  best parameters

Fitting 2 folds for each of 3400 candidates, totalling 6800 fits
Best paramters: {'criterion': 'gini', 'max_depth': 17, 'min_samples_leaf': 5, 'min_samples_split': 10, 'splitter': 'random'})


In [69]:
##Fitting 5 folds for each of 7524 candidates, totalling 37620 fits ---- takes huge time.

In [70]:
tree_cv.best_params_    # getting best parameters from cv

{'criterion': 'gini',
 'max_depth': 17,
 'min_samples_leaf': 5,
 'min_samples_split': 10,
 'splitter': 'random'}

In [71]:
# passing best parameter to decision tree
dt_optimal=DecisionTreeClassifier(criterion='entropy',max_depth=9,min_samples_leaf=7,min_samples_split=7,splitter='random')
dt_optimal.fit(processed_x_train,y_train)

y_pred=dt_optimal.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8070652173913043 
Precision: 0.3953488372093023 
Recall Score: 0.27419354838709675 
F1 Score 0.3238095238095238 
Confusion Matrix: 
 [[280  26]
 [ 45  17]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89       306
           1       0.40      0.27      0.32        62

    accuracy                           0.81       368
   macro avg       0.63      0.59      0.61       368
weighted avg       0.78      0.81      0.79       368



In [72]:
results['DT/HPT'] = [acc,f1]
results

NameError: name 'results' is not defined

## Random Forest Implementation

In [76]:
from sklearn.ensemble import RandomForestClassifier   # importing randomforest

rf_clf = RandomForestClassifier() # Assigning RandomForest CLassifier into variable
rf_clf.fit(processed_x_train,y_train)   # training the data
y_pred=rf_clf.predict(processed_x_test) 

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8478260869565217 
Precision: 0.75 
Recall Score: 0.14516129032258066 
F1 Score 0.24324324324324326 
Confusion Matrix: 
 [[303   3]
 [ 53   9]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       306
           1       0.75      0.15      0.24        62

    accuracy                           0.85       368
   macro avg       0.80      0.57      0.58       368
weighted avg       0.83      0.85      0.80       368



In [85]:
rf_clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=None,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [86]:
results['RF'] = [acc,f1]
results

NameError: name 'results' is not defined

In [87]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=5)]      # List Comprehension-using for loop in list
max_features = ['auto', 'sqrt','log2']        # maximum number of features allowed to try in individual tree
max_depth = [int(x) for x in np.linspace(10, 110, num=5)]            # List Comprehension-using for loop in list
max_depth.append(None)
min_samples_split = [5,7,10,13]          # minimum number of samples required to split an internal node
min_samples_leaf = [2, 4]              # minimum number of samples required to be at a leaf node.

#dictionary for hyperparameters
random_grid = {'n_estimators': n_estimators, 'max_features': max_features,
               'max_depth': max_depth, 'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf_clf1 = RandomForestClassifier(random_state=42)   # Loading the model

rf_cv = RandomizedSearchCV(estimator=rf_clf1, scoring='f1',param_distributions= random_grid, cv=2,
                               verbose=2, n_jobs=-1)

NameError: name 'np' is not defined

In [88]:
np.linspace(200,2000,5)

NameError: name 'np' is not defined

In [89]:
rf_cv.fit(processed_x_train, y_train)
rf_best_params = rf_cv.best_params_ 
print(f"Best paramters: {rf_best_params})") 

NameError: name 'rf_cv' is not defined

In [90]:
# passing best parameter to randomforest
rf_clf2 = RandomForestClassifier(n_estimators=1550,min_samples_leaf=2,min_samples_split=7,max_features="sqrt",max_depth=60)
rf_clf2.fit(processed_x_train, y_train)  # train with tune parameters

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=60, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=2,
                       min_samples_split=7, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=1550, n_jobs=None,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [91]:
y_pred=rf_clf2.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.845108695652174 
Precision: 0.7272727272727273 
Recall Score: 0.12903225806451613 
F1 Score 0.2191780821917808 
Confusion Matrix: 
 [[303   3]
 [ 54   8]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.91       306
           1       0.73      0.13      0.22        62

    accuracy                           0.85       368
   macro avg       0.79      0.56      0.57       368
weighted avg       0.83      0.85      0.80       368



In [92]:
results['RF/HPT'] = [acc,f1]
results

NameError: name 'results' is not defined

## Bagging

In [93]:
from sklearn.ensemble import BaggingClassifier  #import bagging 
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

KNN=KNeighborsClassifier()
LR=LogisticRegression()

model_bagg=BaggingClassifier(estimator=KNN,n_estimators=20) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners

model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

In [94]:
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8342391304347826 
Precision: 0.5333333333333333 
Recall Score: 0.12903225806451613 
F1 Score 0.2077922077922078 
Confusion Matrix: 
 [[299   7]
 [ 54   8]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       306
           1       0.53      0.13      0.21        62

    accuracy                           0.83       368
   macro avg       0.69      0.55      0.56       368
weighted avg       0.79      0.83      0.79       368



In [95]:
results['Bag/KNN'] = [acc,f1]
results

NameError: name 'results' is not defined

In [96]:
model_bagg

BaggingClassifier(bootstrap=True, bootstrap_features=False,
                  estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                                 metric='minkowski',
                                                 metric_params=None,
                                                 n_jobs=None, n_neighbors=5,
                                                 p=2, weights='uniform'),
                  max_features=1.0, max_samples=1.0, n_estimators=20,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [97]:
model_bagg=BaggingClassifier(estimator=LR,n_estimators=50) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners
model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8668478260869565 
Precision: 0.6382978723404256 
Recall Score: 0.4838709677419355 
F1 Score 0.5504587155963303 
Confusion Matrix: 
 [[289  17]
 [ 32  30]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       306
           1       0.64      0.48      0.55        62

    accuracy                           0.87       368
   macro avg       0.77      0.71      0.74       368
weighted avg       0.86      0.87      0.86       368



In [98]:
results['Bag/LR'] = [acc,f1]
results

NameError: name 'results' is not defined

In [99]:
model_bagg=BaggingClassifier(estimator=LR,n_estimators=50,max_samples=0.7,max_features=0.7,bootstrap_features=True) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners
model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.845108695652174 
Precision: 0.8571428571428571 
Recall Score: 0.0967741935483871 
F1 Score 0.17391304347826086 
Confusion Matrix: 
 [[305   1]
 [ 56   6]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91       306
           1       0.86      0.10      0.17        62

    accuracy                           0.85       368
   macro avg       0.85      0.55      0.54       368
weighted avg       0.85      0.85      0.79       368



In [100]:
results['Bag/LR/Smpl'] = [acc,f1]
results

NameError: name 'results' is not defined

### Boosting and XG Boosting

In [73]:
from sklearn.ensemble import GradientBoostingClassifier  # Importing GradientBoostingClassifier
gbm=GradientBoostingClassifier() ## object creation
gbm.fit(processed_x_train,y_train) ## fitting the data

y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.875 
Precision: 0.7666666666666667 
Recall Score: 0.3709677419354839 
F1 Score 0.5 
Confusion Matrix: 
 [[299   7]
 [ 39  23]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.77      0.37      0.50        62

    accuracy                           0.88       368
   macro avg       0.83      0.67      0.71       368
weighted avg       0.86      0.88      0.86       368



In [74]:
gbm

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [75]:
results['GB'] = [acc,f1]
results

NameError: name 'results' is not defined

In [53]:
## Hyperparameter tuning for GradientBoost
# Importing RandomizedSearchCV from sklearn
from sklearn.model_selection import RandomizedSearchCV

# Define Parameters grid for learning_rate, max_depth, n_estimators
param_grid = {
    'learning_rate': [0.01, 0.03, 0.06, 0.1, 0.4, 0.5, 0.6, 0.7],
    'max_depth': [5, 6, 7, 8, 9, 10],
    'n_estimators': [50, 65, 80, 100]
}
GB=GradientBoostingClassifier()  # Assigning GradientBoostingClassifier model into variables

rcv= RandomizedSearchCV(estimator=GB, scoring='f1',refit = True,param_distributions=param_grid, cv=5,
                               verbose=2, n_jobs=-1)
rcv.fit(processed_x_train,y_train)
rcv.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'n_estimators': 50, 'max_depth': 5, 'learning_rate': 0.5}

In [54]:
GB2=GradientBoostingClassifier(n_estimators=100, max_depth=7, learning_rate=0.4)
GB2.fit(processed_x_train,y_train)

y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.875 
Precision: 0.7666666666666667 
Recall Score: 0.3709677419354839 
F1 Score 0.5 
Confusion Matrix: 
 [[299   7]
 [ 39  23]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.77      0.37      0.50        62

    accuracy                           0.88       368
   macro avg       0.83      0.67      0.71       368
weighted avg       0.86      0.88      0.86       368



In [55]:
results['GB/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.777174       1.0  0.807065  0.855978  0.842391  0.847826   
F1        0.378788       1.0  0.413223  0.453608  0.236842  0.222222   

           Bag/KNN    Bag/LR  Bag/LR/Smpl     GB  GB/HPT  
Accuracy  0.834239  0.864130     0.853261  0.875   0.875  
F1        0.186667  0.528302     0.250000  0.500   0.500

## XGBoosting

In [56]:
#!pip install xgboost #installing model XGBOOST
## model creation
from xgboost import XGBClassifier#importing the model library
xgb_r=XGBClassifier() ## object creation
xgb_r.fit(processed_x_train,y_train)# fitting the data
y_pred=xgb_r.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8559782608695652 
Precision: 0.6666666666666666 
Recall Score: 0.2903225806451613 
F1 Score 0.4044943820224719 
Confusion Matrix: 
 [[297   9]
 [ 44  18]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       306
           1       0.67      0.29      0.40        62

    accuracy                           0.86       368
   macro avg       0.77      0.63      0.66       368
weighted avg       0.84      0.86      0.83       368



In [57]:
xgb_r

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='binary:logistic', ...)

In [58]:
results['XGB'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.777174       1.0  0.807065  0.855978  0.842391  0.847826   
F1        0.378788       1.0  0.413223  0.453608  0.236842  0.222222   

           Bag/KNN    Bag/LR  Bag/LR/Smpl     GB  GB/HPT       XGB  
Accuracy  0.834239  0.864130     0.853261  0.875   0.875  0.855978  
F1        0.186667  0.528302     0.250000  0.500   0.500  0.404494

In [59]:
#Hyperparameter tuning
param_grid = {'gamma': [0,0.1,0.2,0.4],
              'learning_rate': [0.01, 0.03, 0.06, 0.1],
              'max_depth': [5,6,7,8,9],
              'n_estimators': [50,65,80],
              'reg_alpha': [0,0.1,0.2,0.4],
              'reg_lambda': [0,0.1,0.2]}

XGB=XGBClassifier(random_state=42,verbosity=0,silent=0)  # Assigning XGBClassifier model into variables
rcv= GridSearchCV(estimator=XGB, scoring='f1',refit=True,param_grid=param_grid,  cv=3,
                               verbose=1, n_jobs=-1)
rcv.fit(processed_x_train,y_train)
rcv.best_params_

Fitting 3 folds for each of 2880 candidates, totalling 8640 fits


{'gamma': 0.2,
 'learning_rate': 0.1,
 'max_depth': 7,
 'n_estimators': 80,
 'reg_alpha': 0.1,
 'reg_lambda': 0.2}

In [60]:
XGB2=XGBClassifier(reg_lambda= 0.1, reg_alpha= 0.1, n_estimators=50, max_depth=8, learning_rate=0.1, gamma=0)
XGB2.fit(processed_x_train,y_train)
y_pred=XGB2.predict(processed_x_test)#testing

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.842391304347826 
Precision: 0.5833333333333334 
Recall Score: 0.22580645161290322 
F1 Score 0.32558139534883723 
Confusion Matrix: 
 [[296  10]
 [ 48  14]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91       306
           1       0.58      0.23      0.33        62

    accuracy                           0.84       368
   macro avg       0.72      0.60      0.62       368
weighted avg       0.81      0.84      0.81       368



In [61]:
results['XGB/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.777174       1.0  0.807065  0.855978  0.842391  0.847826   
F1        0.378788       1.0  0.413223  0.453608  0.236842  0.222222   

           Bag/KNN    Bag/LR  Bag/LR/Smpl     GB  GB/HPT       XGB   XGB/HPT  
Accuracy  0.834239  0.864130     0.853261  0.875   0.875  0.855978  0.842391  
F1        0.186667  0.528302     0.250000  0.500   0.500  0.404494  0.325581

In [62]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(processed_x_train,y_train)

y_pred=LR.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8668478260869565 
Precision: 0.6382978723404256 
Recall Score: 0.4838709677419355 
F1 Score 0.5504587155963303 
Confusion Matrix: 
 [[289  17]
 [ 32  30]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       306
           1       0.64      0.48      0.55        62

    accuracy                           0.87       368
   macro avg       0.77      0.71      0.74       368
weighted avg       0.86      0.87      0.86       368



In [63]:
## Data Balancing and Creating Model
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)
LR.fit(x_smote,y_smote)

y_pred=LR.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.7554347826086957 
Precision: 0.3870967741935484 
Recall Score: 0.7741935483870968 
F1 Score 0.5161290322580645 
Confusion Matrix: 
 [[230  76]
 [ 14  48]]
              precision    recall  f1-score   support

           0       0.94      0.75      0.84       306
           1       0.39      0.77      0.52        62

    accuracy                           0.76       368
   macro avg       0.66      0.76      0.68       368
weighted avg       0.85      0.76      0.78       368

